USE [master]
GO
/****** Object:  Database [CampanhaVacinacaoDB]    Script Date: 29/06/2023 23:04:08 ******/
CREATE DATABASE [CampanhaVacinacaoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CampanhaVacinacaoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CampanhaVacinacaoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CampanhaVacinacaoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CampanhaVacinacaoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CampanhaVacinacaoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET  MULTI_USER 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CampanhaVacinacaoDB]
GO
/****** Object:  Table [dbo].[Relatorios]    Script Date: 29/06/2023 23:04:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Relatorios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DataSolicitacao] [datetime] NOT NULL,
	[Descricao] [nvarchar](100) NOT NULL,
	[DataAplicacao] [datetime] NOT NULL,
	[QuantidadeTotalVacinados] [int] NOT NULL,
	[SolicitanteId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Solicitantes]    Script Date: 29/06/2023 23:04:08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Solicitantes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nvarchar](100) NOT NULL,
	[CPF] [nvarchar](11) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UX_Solicitante_CPF]    Script Date: 29/06/2023 23:04:08 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UX_Solicitante_CPF] ON [dbo].[Solicitantes]
(
	[CPF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Relatorios]  WITH CHECK ADD FOREIGN KEY([SolicitanteId])
REFERENCES [dbo].[Solicitantes] ([Id])
GO
USE [master]
GO
ALTER DATABASE [CampanhaVacinacaoDB] SET  READ_WRITE 
GO
